name: Node.js CI


jobs:
  build:
    runs-on: ubuntu-latest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm test
